export const committees = [
  {
    id: "bilateral",
    abbr: null,
    tag: "Indo-Nepal Bilateral Meet",
    name: "Indo–Nepal Bilateral Meet",
    subtitle: "The Himalayan Dialogue",
    description:
      "The committee unique to INDYS and to no other MUN conference in the world. Indian and Nepali delegates negotiate directly — trade, transit, water rights, and people-to-people connectivity — as representatives of their own nations. This is not simulation. This is the relationship this conference was built to strengthen.",
    logo: "/brand/indo-nepal-bilateral-mark.png",
    logoAlt: "Indo-Nepal Bilateral Meet flags",
    featured: true,
    span: "full",
    heroImage: "/committees/bilateral-hero.jpg",
    difficulty: "Expert",
    seats: "30 (15 per side)",
    format: "Bilateral Negotiation",
    agenda: [
      "Revision of the 1950 Treaty of Peace and Friendship",
      "Hydropower cooperation — Mahakali, Koshi, and Gandaki river accords",
      "Trade facilitation and transit rights for Nepal",
    ],
  },
  {
    id: "unsc",
    abbr: "UNSC",
    tag: null,
    name: "UN Security Council",
    subtitle: null,
    description:
      "The crown jewel of any MUN program. Chosen with a specifically regional agenda — Himalayan border tensions, water rights disputes, and the India-China-Nepal triangle. Only 15 delegates, intense debate, highest difficulty. The most coveted committee at the summit.",
    logo: "/brand/un-emblem.png",
    logoAlt: "United Nations committee mark",
    featured: false,
    span: "single",
    heroImage: "/committees/unsc-hero.jpg",
    difficulty: "Expert",
    seats: "15",
    format: "UN Formal Procedure",
    agenda: [
      "Himalayan border tensions and the India–China–Nepal strategic triangle",
      "Transboundary water security in the Brahmaputra and Ganges basins",
    ],
  },
  {
    id: "unhcr",
    abbr: "UNHCR",
    tag: null,
    name: "UN High Commissioner for Refugees",
    subtitle: "United Nations Refugee Agency",
    description:
      "An operational pillar of the global humanitarian response. Delegates respond to complex humanitarian crises — large-scale displacement, dynamic political situations, climate change, and refugee flow — while providing aid, protection, and advocacy for millions.",
    logo: "/brand/unhcr-mark.png",
    logoAlt: "UNHCR committee mark",
    featured: false,
    span: "single",
    heroImage: "/committees/unhcr-hero.jpg",
    difficulty: "Advanced",
    seats: "Up to 80",
    format: "UN Formal Procedure",
    agenda: [
      "Climate displacement and statelessness in the Bay of Bengal region",
      "Protection frameworks for internally displaced persons in South Asia",
    ],
  },
  {
    id: "uncsw",
    abbr: "UNCSW",
    tag: null,
    name: "UN Commission on the Status of Women",
    subtitle: null,
    description:
      "Essential for inclusivity and for attracting women-focused brand sponsors. South Asia is one of the world's worst regions for female economic participation — this committee is personally relevant for every delegate from India and Nepal. High emotion, high quality of debate.",
    logo: "/brand/un-women.png",
    logoAlt: "UN Women committee mark",
    featured: false,
    span: "single",
    heroImage: "/committees/uncsw-hero.jpg",
    difficulty: "Advanced",
    seats: "Up to 70",
    format: "UN Formal Procedure",
    agenda: [
      "Female economic participation and the gender wage gap in South Asia",
      "Legal reform and accountability for gender-based violence in conflict zones",
    ],
  },
  {
    id: "disec",
    abbr: "DISEC",
    tag: null,
    name: "Disarmament & Security",
    subtitle: "UNGA First Committee",
    description:
      "The UNGA First Committee for Disarmament & Security. Delegates confront autonomous weapons, cyber warfare, arms control, and the regional security questions shaping the wider Indo-Nepal and South Asian landscape.",
    logo: "/brand/un-emblem.png",
    logoAlt: "United Nations committee mark",
    featured: false,
    span: "single",
    heroImage: "/committees/disec-hero.jpg",
    difficulty: "Advanced",
    seats: "Up to 80",
    format: "UN Formal Procedure",
    agenda: [
      "Regulation of autonomous weapons systems and AI in armed conflict",
      "Cyber warfare norms and digital arms control in the Indo-Pacific",
    ],
  },
  {
    id: "aippm",
    abbr: "AIPPM",
    tag: null,
    name: "All India Political Parties Meet",
    subtitle: "Indian Parliament",
    description:
      "Delegates simulate Indian political parties debating a live, real-world issue — the renegotiation of the foundational India-Nepal treaty. High drama, high context, very shareable content.",
    logo: "/brand/aippm-mark.png",
    logoAlt: "Indian Parliament committee mark",
    featured: false,
    span: "single",
    heroImage: "/committees/aippm-hero.jpg",
    difficulty: "Intermediate",
    seats: "Up to 45",
    format: "Indian Parliamentary Procedure",
    agenda: [
      "Renegotiation of the India–Nepal Treaty of Peace and Friendship (1950)",
    ],
  },
  {
    id: "unctad",
    abbr: "UNCTAD",
    tag: null,
    name: "UN Conference on Trade and Development",
    subtitle: "Trade. Development. Prosperity for All.",
    description:
      "UNCTAD is the United Nations' leading forum dedicated to shaping a fairer and more inclusive global economy. Delegates deliberate on trade, investment, finance, and sustainable development to help economies grow, connect, and prosper together.",
    logo: "/brand/un-emblem.png",
    logoAlt: "United Nations committee mark",
    featured: false,
    span: "single",
    heroImage: "/committees/unctad-hero.jpg",
    difficulty: "Intermediate",
    seats: "Up to 80",
    format: "UN Formal Procedure",
    agenda: [
      "Digital trade and cross-border e-commerce frameworks for developing nations",
      "Technology transfer, intellectual property, and the Global South development gap",
    ],
  },
  {
    id: "ictr",
    abbr: "ICTR",
    tag: null,
    name: "International Criminal Tribunal for Rwanda",
    subtitle: "Historical Tribunal",
    description:
      "A fully simulated criminal tribunal prosecuting cases arising from the 1994 Rwandan Genocide. Delegates serve as prosecution, defence, and judicial bench as evidence is examined, testimony is cross-questioned, and verdicts are delivered.",
    logo: "/brand/un-emblem.png",
    logoAlt: "United Nations committee mark",
    featured: false,
    span: "single",
    heroImage: "/committees/ictr-hero.jpg",
    difficulty: "Advanced",
    seats: "Up to 36",
    format: "Criminal Tribunal Procedure",
    agenda: [
      "Prosecution of crimes against humanity in the 1994 Rwandan Genocide",
      "Establishing precedent for international criminal accountability and transitional justice",
    ],
  },
  {
    id: "ccc",
    abbr: "CCC",
    tag: null,
    name: "Continuous Crisis Committee",
    subtitle: "Crisis Room",
    description:
      "A committee that never sleeps. The CCC runs a live, escalating global crisis across all three conference days — new developments injected every 60 minutes, alliances shifting in real time, and consequences accumulating session by session.",
    logo: "/brand/crisis-room.png",
    logoAlt: "Crisis Room committee mark",
    featured: false,
    span: "single",
    heroImage: "/committees/ccc-hero.jpg",
    difficulty: "Expert",
    seats: "Up to 25",
    format: "Crisis Committee",
    agenda: [
      "Classified — evolving real-time geopolitical crisis scenario",
      "New developments injected every 60 minutes across all three conference days",
    ],
  },
  {
    id: "oic",
    abbr: "OIC",
    tag: null,
    name: "Organisation of Islamic Cooperation",
    subtitle: "Regional Body",
    description:
      "Representing 57 member states and 1.8 billion people, the OIC adds a crucial dimension of religious geopolitics and humanitarian crisis management, challenging delegates to represent worldviews very different from their own.",
    logo: "/brand/oic-mark.png",
    logoAlt: "OIC committee mark",
    featured: false,
    span: "single",
    heroImage: "/committees/oic-hero.jpg",
    difficulty: "Intermediate",
    seats: "Up to 57",
    format: "Inter-Governmental Body Procedure",
    agenda: [
      "The Rohingya humanitarian crisis and regional displacement in Southeast Asia",
      "Economic solidarity, halal trade, and development finance within the Islamic world",
    ],
  },
  {
    id: "ipc",
    abbr: "IPC",
    tag: null,
    name: "International Press Corps",
    subtitle: "Creative Press Corps",
    description:
      "Not a committee — a media machine. IPC delegates cover all other committees in real time, producing articles, photographs, and caricatures that get published in the INDYS gazette. This corps creates the summit's visual and written record.",
    logo: "/brand/creative-press-corps.png",
    logoAlt: "Creative Press Corps committee mark",
    featured: false,
    span: "double",
    heroImage: "/committees/ipc-hero.jpg",
    difficulty: "Open",
    seats: "Up to 40",
    format: "Creative Press Corps",
    agenda: [
      "Real-time media coverage of all ten INDYS committees",
      "Production of the official INDYS Summit Gazette — journalism, photography, caricature",
    ],
  },
] as const;

export const stats = [
  { num: "500+", label: "Total Delegates", sub: "Students from 30+ schools across India and Nepal" },
  { num: "10",   label: "Committees",       sub: "UN bodies, regional forums, crisis simulations and press" },
  { num: "3",    label: "Conference Days",  sub: "Nov 20, 21 & 22 — full committee sessions each day" },
  { num: "1",    label: "Historic First",   sub: "First authorized bilateral India–Nepal MUN conference" },
] as const;

export const reasons = [
  {
    num: "1",
    heading: "Nepal's border crossing is 30 km away",
    body: "The Panitanki–Kakarbhitta crossing — India's most active Nepal border crossing — is under 30 km from the city centre. No delegate travels far to reach INDYS.",
  },
  {
    num: "2",
    heading: "Nepal's Consulate General is here",
    body: "The Consulate General of Nepal has its permanent headquarters in Siliguri — an extraordinary distinction that gives INDYS direct access to official bilateral diplomatic channels.",
  },
  {
    num: "3",
    heading: "Gateway to four nations",
    body: "Siliguri sits at the junction of India, Nepal, Bhutan, and Bangladesh. No other city in India has this four-nation geographic significance.",
  },
  {
    num: "4",
    heading: "Hub of Indo–Nepal bilateral commerce",
    body: "Siliguri is the de facto capital of Indo–Nepal trade, transit, and logistics. The economic relationship INDYS's committees debate is the same one that built this city.",
  },
] as const;

export const casePoints = [
  {
    num: "01",
    heading: "Geopolitical Timing",
    body: "Nepal's new government, India's Neighbourhood First policy, and China's growing influence in eastern Nepal create a once-in-a-decade window for youth diplomacy programming at this border.",
  },
  {
    num: "02",
    heading: "Unique Geography",
    body: "Siliguri borders Nepal, Bhutan, and Bangladesh and is the only gateway to Northeast India. No other city provides this bilateral narrative — the venue itself is the statement.",
  },
  {
    num: "03",
    heading: "Real Talent Pipeline",
    body: "Delegates are Class 9–12 and undergraduate students — exactly the demographic that institutions, universities, and brands compete to reach early. This is where future policymakers are found first.",
  },
  {
    num: "04",
    heading: "Built-in Press Corps",
    body: "An International Press Corps with Journalism, Photography, and Caricature sub-tracks means every sponsor's presence is documented, reported, and amplified by the delegates themselves.",
  },
  {
    num: "05",
    heading: "Unrivaled Networking",
    body: "The summit acts as a unique crossroads, bringing together top-tier students, seasoned diplomats, academic experts, and corporate leaders for mentorship, recruitment, and high-level institutional collaboration.",
  },
] as const;

export const tiers = [
  {
    id: "platinum",
    name: "Platinum",
    role: "Title Partner",
    category: "Schools · Banks · Real Estate · Hotels",
    perks: [
      "Name in summit title",
      "Stage branding",
      "Opening keynote slot",
      "Banner at all venues",
      "Logo on all materials",
      "Gazette front page",
      "Social media feature",
      "Delegate kit inclusion",
    ],
  },
  {
    id: "gold",
    name: "Gold",
    role: "Powered By",
    category: "Coaching · EdTech · Retail · FMCG",
    perks: [
      "Stage banner",
      "Logo on certificates",
      "Stall at venue",
      "Social media posts (3)",
      "Delegate kit inclusion",
      "Gazette inside page",
    ],
  },
  {
    id: "silver",
    name: "Silver",
    role: "Associate Partner",
    category: "Local brands · Restaurants · Services",
    perks: [
      "Logo on banners",
      "Social media post (1)",
      "Gazette mention",
    ],
  },
  {
    id: "venue",
    name: "Venue Partner",
    role: "Host / Venue Partner",
    category: "Schools in Siliguri & North Bengal",
    perks: [
      "Designated home committee",
      "Host school branding",
      "Principal on stage",
      "Priority delegate spots",
      "Media coverage",
      "MOU with INDYS",
    ],
  },
] as const;
